from pydantic import BaseModel, Field
from app.schemas.common import BaseResponse

class VqaJsonRequest(BaseModel):
    image_base64: str = Field(..., description="Base64 encoded string of the target image")
    question: str = Field(..., description="The question about the image to answer")

class VqaResult(BaseResponse):
    question: str = Field(..., description="The submitted question")
    answer: str = Field(..., description="The answered text generated by the model")
